[package]
name = "proc-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = "1"
darling = "0.21.3"
Inflector = "0.11.4"
